spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create